// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jebgzbbqttbmkeloutwc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImplYmd6YmJxdHRibWtlbG91dHdjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzNDU5NjcsImV4cCI6MjA2OTkyMTk2N30.qXmX-W0LcVh8MVhGxYur6gXVuva2NPzCyPFX9gPUFR8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});