// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sukjhodekowdfmqimiyo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN1a2pob2Rla293ZGZtcWltaXlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3Mjc5MDcsImV4cCI6MjA3MjMwMzkwN30.rhOYzIk2YS3YqZ1fiVxjpV0v2YvhMo-vmuIiQpJFHdE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});